import React, { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Eczar } from 'next/font/google';
import './globals.css';
import Header from '@/components/Layout/Header';
import Footer from '@/components/Layout/Footer';
import background from '../../public/background.jpg';

const eczar = Eczar({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-eczar',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={eczar.variable} style={{ backgroundImage: `url(${background.src})` }}>
        <div className="flex h-screen flex-col justify-between font-sans">
          <Header />
          <main className="mb-auto mx-auto flex-1 px-4 lg:px-48 container">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
